export const Users = [
  {
    id: 1,
    profilePicture: "assets/People/1.jpeg",
    username: "Woofy",
  },
  {
    id: 2,
    profilePicture: "assets/People/2.jpeg",
    username: "Mr dog",
  },
  {
    id: 3,
    profilePicture: "assets/People/3.jpeg",
    username: "Clifford",
  },
  {
    id: 4,
    profilePicture: "assets/People/10.jpg",
    username: "Azula",
  },
  {
    id: 5,
    profilePicture: "assets/People/5.jpeg",
    username: "Awoo",
  },
  {
    id: 6,
    profilePicture: "assets/People/6.jpeg",
    username: "Woofer",
  },
  {
    id: 7,
    profilePicture: "assets/People/7.jpeg",
    username: "Barky",
  },
  {
    id: 8,
    profilePicture: "assets/People/8.jpeg",
    username: "My Paws",
  },
  {
    id: 9,
    profilePicture: "assets/People/9.jpeg",
    username: "Mr Husky",
  },
  {
    id: 10,
    profilePicture: "assets/People/4.jpg",
    username: "Ruff",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/Posts/toys.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/Posts/puppy_toys.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/Posts/fresh_treats.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    desc: "Check out these sweet bully sticks owner got me",
    photo: "assets/Posts/bully-sticks.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/Posts/bone.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/Posts/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/Posts/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/Posts/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/Posts/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/Posts/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
